#!/bin/bash
BOT="/root/openasset_club/telegram_bot"
M="$BOT/main.py"
echo "════ DIAGNOSTIC 2 ════"
echo ""
echo "── A. Deployed dashboard uses back_home? ──"
grep -c "back_home" "$BOT/trading_dashboard.py" && echo "  (count of back_home in dashboard)"
grep -c "main_menu" "$BOT/trading_dashboard.py" && echo "  (count of main_menu — should be 0)"
echo ""
echo "── B. start() function (lines 84-160) ──"
sed -n '84,160p' "$M"
echo ""
echo "── C. button_callback start + back_home (lines 160-300) ──"
sed -n '160,300p' "$M"
echo "════ END ════"
